import type { StatusType } from "../constants";

/**
 * Represents a job application entry.
 *
 * Fields:
 *     id (string)           - UUID, generated by backend
 *     company (string)      - Company name
 *     role (string)         - Job title/position
 *     status (StatusType)   - One of: 'applied', 'interview', 'offer', 'rejected'
 *     link (string)         - Optional, URL to job posting
 *     dateApplied (string)  - Optional, ISO date string
 *     notes (string)        - Optional, personal notes
 *     description (string)  - Optional, job description for AI resume generation
 */
export interface JobApplication {
  id: string;
  company: string;
  role: string;
  status: StatusType;
  link?: string;
  dateApplied?: string;
  notes?: string;
  description?: string;
}

// Re-export StatusType as ApplicationStatus for semantic clarity
export type ApplicationStatus = StatusType;

// Input types for API operations (id excluded - backend generates it)
export type CreateApplicationInput = Omit<JobApplication, 'id'>;
export type UpdateApplicationInput = Omit<JobApplication, 'id'>;
